/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CaixaControle;
import controle.UsuarioControle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Caixa;
import modelo.CaixaStatus;
import modelo.UserTipo;
import modelo.Usuario;

/**
 *
 * @author zscrollock
 */
public class ViewAbrir_Caixa extends javax.swing.JDialog {

    private Usuario user;
    private Caixa caixa;
    /**
     * Creates new form ViewAbrir_Caixa
     */
    public ViewAbrir_Caixa(java.awt.Frame parent, boolean modal, Usuario user) {
        super(parent, modal);
        initComponents();
        this.user = user;
        this.setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent we){
                jPanel1.setVisible(true);
                jPanel2.setVisible(true);
                jLabel_valor.setVisible(true);
                jTextField_valor.setVisible(true);
                jButton1.setVisible(true);
                
                CaixaControle c_control = new CaixaControle();
                List<Caixa> l = c_control.isOpen();
                //[] Anterior Fechado
                //[...] Anterior Aberto        
                if(!l.isEmpty()){
                    caixa = l.get(l.size()-1);
                    

                    if(caixa.getStatus().equals(CaixaStatus.ABERTO)){
                        dispose();
                        ViewMenuPrincipal menu = new ViewMenuPrincipal(null, false, user, caixa);
                        menu.setTitle("Menu Principal - Software GEP");
                        menu.setVisible(true);
                    }
                }else{

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_prin = new javax.swing.JPanel();
        jLabel_valor = new javax.swing.JLabel();
        jTextField_valor = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Abertura de Caixa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel_prin.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_valor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_valor.setText("Digite o Valor de Abertura do Caixa");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Abrir Caixa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF do Gerente");

        javax.swing.GroupLayout jPanel_prinLayout = new javax.swing.GroupLayout(jPanel_prin);
        jPanel_prin.setLayout(jPanel_prinLayout);
        jPanel_prinLayout.setHorizontalGroup(
            jPanel_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_prinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_prinLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_prinLayout.createSequentialGroup()
                        .addGroup(jPanel_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_valor)
                            .addGroup(jPanel_prinLayout.createSequentialGroup()
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))))
        );
        jPanel_prinLayout.setVerticalGroup(
            jPanel_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_prinLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_prin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float valor = Float.parseFloat(jTextField_valor.getText());
        String cpf_aux = jFormattedTextField1.getText();
        UsuarioControle user_control = new UsuarioControle();
        CaixaControle c_control = new CaixaControle();
        List<Usuario> l;
        caixa = new Caixa();
        l = user_control.findByCpf(cpf_aux);
        Usuario aux = new Usuario();
        if(!jTextField_valor.getText().equals("") || !jFormattedTextField1.getText().equals("")){
            if(!jTextField_valor.getText().equals(" ") || !jFormattedTextField1.getText().equals(" ")){
                if(!l.isEmpty()){
                    aux = l.get(l.size()-1);
                    if(aux.getTipo().equals(UserTipo.GERENTE) || aux.getTipo().equals(UserTipo.ADMINISTRADOR)){
                        caixa.setDataCaixa(new Date());
                        caixa.setSaldo_abertura(valor);
                        caixa.setSaldo_fechamento(valor);
                        caixa.setStatus(CaixaStatus.ABERTO);
                        
                        c_control.inserir(caixa);
                        this.dispose();
                        ViewMenuPrincipal menu = new ViewMenuPrincipal(null, false, user, caixa);
                        menu.setTitle("Menu Principal - Software GEP");
                        menu.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "Esse usuario não é Gerente", "Alerta", JOptionPane.WARNING_MESSAGE);
                        jFormattedTextField1.requestFocus();
                        jFormattedTextField1.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Informe um CPF de Gerente Valido","Alerta", JOptionPane.WARNING_MESSAGE);
                    jFormattedTextField1.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_prin;
    private javax.swing.JTextField jTextField_valor;
    // End of variables declaration//GEN-END:variables
}
