/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.UsuarioControle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.UserTipo;
import modelo.Usuario;

/**
 *
 * @author zscrollock
 */
public class ViewLogin extends javax.swing.JFrame {

    private UsuarioControle user_controle;
    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        user_controle = new UsuarioControle();
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent we){
                Date dataAtual = Calendar.getInstance().getTime();
                DateFormat dateFormat = new SimpleDateFormat("dd - MM - yyyy hh:mm:ss");
                jLabel_data_hora.setText(dateFormat.format(dataAtual));
            }
        });
        this.setLocationRelativeTo(null);
        buttonGroup1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_corpo = new javax.swing.JPanel();
        jPanel_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText_login = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRadioButton_ADM = new javax.swing.JRadioButton();
        jRadioButton_Gerente = new javax.swing.JRadioButton();
        jRadioButton_Funcionario = new javax.swing.JRadioButton();
        label_esq_senha = new javax.swing.JLabel();
        jButton_logar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel_boasVindas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_data_hora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software GEP");
        setResizable(false);

        jPanel_corpo.setBackground(new java.awt.Color(255, 102, 0));

        jPanel_login.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/Webp.net-resizeimage (1).png"))); // NOI18N

        jText_login.setText("Digite o Login");
        jText_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jText_loginFocusGained(evt);
            }
        });

        jPasswordField1.setText("senha senha senha");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });

        buttonGroup1.add(jRadioButton_ADM);
        jRadioButton_ADM.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jRadioButton_ADM.setText("Administrador");

        buttonGroup1.add(jRadioButton_Gerente);
        jRadioButton_Gerente.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jRadioButton_Gerente.setText("Gerente");

        buttonGroup1.add(jRadioButton_Funcionario);
        jRadioButton_Funcionario.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jRadioButton_Funcionario.setText("Funcionario");

        label_esq_senha.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        label_esq_senha.setForeground(new java.awt.Color(0, 0, 0));
        label_esq_senha.setText("Esqueci minha senha");
        label_esq_senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_esq_senhaMouseClicked(evt);
            }
        });

        jButton_logar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_logar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logar.setText("Logar");
        jButton_logar.setToolTipText("");
        jButton_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Primeiro Acesso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jText_login, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addComponent(jRadioButton_ADM, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_esq_senha)
                            .addGroup(jPanel_loginLayout.createSequentialGroup()
                                .addComponent(jButton_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jText_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_ADM)
                    .addComponent(jRadioButton_Funcionario)
                    .addComponent(jRadioButton_Gerente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_esq_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_logar)
                    .addComponent(jButton1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel_boasVindas.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_boasVindas.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seja bem vindo ao Software GEP");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data atual: ");

        jLabel_data_hora.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_data_hora.setText("dd/mm/aaaa");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desenvolvido por: Luís Augusto C. Mota");

        javax.swing.GroupLayout jPanel_boasVindasLayout = new javax.swing.GroupLayout(jPanel_boasVindas);
        jPanel_boasVindas.setLayout(jPanel_boasVindasLayout);
        jPanel_boasVindasLayout.setHorizontalGroup(
            jPanel_boasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_boasVindasLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel_boasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel_boasVindasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_data_hora)))
                .addGap(71, 71, 71))
            .addGroup(jPanel_boasVindasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_boasVindasLayout.setVerticalGroup(
            jPanel_boasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_boasVindasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_boasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_data_hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_corpoLayout = new javax.swing.GroupLayout(jPanel_corpo);
        jPanel_corpo.setLayout(jPanel_corpoLayout);
        jPanel_corpoLayout.setHorizontalGroup(
            jPanel_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_corpoLayout.createSequentialGroup()
                .addComponent(jPanel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel_boasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel_corpoLayout.setVerticalGroup(
            jPanel_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_corpoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel_boasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_corpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_corpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_loginFocusGained
        // TODO add your handling code here:
        jText_login.setText("");
    }//GEN-LAST:event_jText_loginFocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jButton_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logarActionPerformed
        // TODO add your handling code here:
        List<Usuario> usuario;
        Usuario user = new Usuario();
        String login = jText_login.getText().trim();
        String senha = new String(jPasswordField1.getPassword());
        
        if(!login.equals("") || !senha.equals("")){
            if(jRadioButton_ADM.isSelected()){
                usuario = user_controle.find(login, senha, UserTipo.ADMINISTRADOR);
                if(!usuario.isEmpty()){
                    user = usuario.get(usuario.size()-1);
                    ViewAbrir_Caixa t_abrir = new ViewAbrir_Caixa(null, false, user);
                    this.dispose();
                    t_abrir.setTitle("Abertura de Caixa");
                    t_abrir.setVisible(true);
                    //Abertura da Tela principal de Menu
                }else{
                   JOptionPane.showMessageDialog(null, "Usuario NÃO Existe e/ou NÃO foi encontrado", "Alerta", JOptionPane.WARNING_MESSAGE); 
                   jText_login.setText("Digite o Login");
                   jPasswordField1.setText("*************");
                   buttonGroup1.clearSelection();
                }
            }else if(jRadioButton_Gerente.isSelected()){
                usuario = user_controle.find(login, senha, UserTipo.GERENTE);
                if(!usuario.isEmpty()){
                    user = usuario.get(usuario.size()-1);
                    ViewAbrir_Caixa t_abrir = new ViewAbrir_Caixa(null, false, user);
                    t_abrir.setTitle("Abertura de Caixa");
                    this.dispose();
                    t_abrir.setVisible(true);
                }else{
                   JOptionPane.showMessageDialog(null, "Usuario NÃO Existe e/ou NÃO foi encontrado", "Alerta", JOptionPane.WARNING_MESSAGE);
                   jText_login.setText("Digite o Login");
                   jPasswordField1.setText("*************");
                   buttonGroup1.clearSelection();
                }
            }else if(jRadioButton_Funcionario.isSelected()){
                usuario = user_controle.find(login, senha, UserTipo.FUNCIONARIO);
                if(!usuario.isEmpty()){
                    user = usuario.get(usuario.size()-1);
                    ViewAbrir_Caixa t_abrir = new ViewAbrir_Caixa(null, false, user);
                    t_abrir.setTitle("Abertura de Caixa");
                    this.dispose();
                    t_abrir.setVisible(true);
                }else{
                   JOptionPane.showMessageDialog(null, "Usuario NÃO Existe e/ou NÃO foi encontrado", "Alerta", JOptionPane.WARNING_MESSAGE);
                   jText_login.setText("Digite o Login");
                   jPasswordField1.setText("*************");
                   buttonGroup1.clearSelection();
                }
            }else if(!jRadioButton_ADM.isSelected() || !jRadioButton_Gerente.isSelected() || !jRadioButton_Funcionario.isSelected()){
                jText_login.setText("Digite o Login");
                jPasswordField1.setText("*************");
                buttonGroup1.clearSelection();
                JOptionPane.showMessageDialog(null, "Selecione o tipo de usuario", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
            jText_login.setText("");
            jPasswordField1.setText("*************");
            buttonGroup1.clearSelection();
        }
       
    }//GEN-LAST:event_jButton_logarActionPerformed

    private void label_esq_senhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_esq_senhaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Consulte o ADMINISTRADOR para restaurar a senha", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_label_esq_senhaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UsuarioControle controle = new UsuarioControle();
        Usuario user = new Usuario();
        List<Usuario> user_search = controle.find("admin", "admin", UserTipo.ADMINISTRADOR);
        if(!user_search.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ja foi feito o primeiro acesso, consulte o gerente", "Alerta", JOptionPane.WARNING_MESSAGE);
        }else{
            user.setCpf("000.000.000-00");
            user.setLogin("admin");
            user.setNome("admin");
            user.setSenha("admin");
            user.setSalario(0);
            user.setTelefone("(00)00000-0000");
            user.setTipo(UserTipo.ADMINISTRADOR);
            controle.inserir(user);
            JOptionPane.showMessageDialog(null, "Primeiro acesso - Login: admin Senha: admin", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_logar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_data_hora;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_boasVindas;
    private javax.swing.JPanel jPanel_corpo;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton_ADM;
    private javax.swing.JRadioButton jRadioButton_Funcionario;
    private javax.swing.JRadioButton jRadioButton_Gerente;
    private javax.swing.JTextField jText_login;
    private javax.swing.JLabel label_esq_senha;
    // End of variables declaration//GEN-END:variables
}
