/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CaixaControle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Caixa;
import modelo.CaixaStatus;
import modelo.UserTipo;
import modelo.Usuario;

/**
 *
 * @author zscrollock
 */
public class ViewMenuPrincipal extends javax.swing.JDialog {

    private Usuario user;
    private JFrame tela_login;
    private Caixa caixa;
    private CaixaControle c_control = new CaixaControle();
    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipal(java.awt.Frame parent, boolean modal, Usuario user, Caixa caixa) {
        super(parent, modal);
        initComponents();
        this.user = user;
        this.caixa = caixa;
        this.setLocationRelativeTo(null);
        
        addWindowListener(new WindowAdapter() {
        @Override
         public void windowOpened(WindowEvent we){                                 
                if(user.getTipo().equals(UserTipo.ADMINISTRADOR) || user.getTipo().equals(UserTipo.GERENTE)){
                    jButton_distribuidores.setVisible(true);
                    jButton_funcionarios.setVisible(true);
                    jButton_produtos.setVisible(true);
                    jButton_venda.setVisible(true);
                    jButton_fechar.setVisible(true);
                }else{
                    jButton_distribuidores.setVisible(false);
                    jButton_funcionarios.setVisible(false);
                    jButton_produtos.setVisible(true);
                    jButton_venda.setVisible(true);
                    jButton_fechar.setVisible(false);
                }
                                
                jTextPane1.setContentType("text/html");
                jTextPane1.setText("<html>             <b>Bem vindo(a) ao Menu Principal do Software GEP</b><br>INFORMAÇÃO GERAL SOBRE O MENU<br> - É possivel se encontrar informações sobre cada funcionalidade ao passar o mouse sobre o botão da mesma.<br> - O sistema foi desenvolvido com o intuito de aprendizagem e desenvolvimento do Projeto Integrador. <br><b>O projeto foi desenvolvido por Luís Augusto Cardoso Mota</b></html>");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton_funcionarios = new javax.swing.JButton();
        jButton_distribuidores = new javax.swing.JButton();
        jButton_produtos = new javax.swing.JButton();
        jButton_venda = new javax.swing.JButton();
        jButton_fechar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 0));

        jButton_funcionarios.setBackground(new java.awt.Color(0, 0, 0));
        jButton_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        jButton_funcionarios.setText("Funcionarios");
        jButton_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_funcionariosMouseEntered(evt);
            }
        });
        jButton_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_funcionariosActionPerformed(evt);
            }
        });

        jButton_distribuidores.setBackground(new java.awt.Color(0, 0, 0));
        jButton_distribuidores.setForeground(new java.awt.Color(255, 255, 255));
        jButton_distribuidores.setText("Distribuidores");
        jButton_distribuidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_distribuidoresMouseEntered(evt);
            }
        });
        jButton_distribuidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_distribuidoresActionPerformed(evt);
            }
        });

        jButton_produtos.setBackground(new java.awt.Color(0, 0, 0));
        jButton_produtos.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos.setText("Estoque");
        jButton_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_produtosMouseEntered(evt);
            }
        });
        jButton_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtosActionPerformed(evt);
            }
        });

        jButton_venda.setBackground(new java.awt.Color(0, 0, 0));
        jButton_venda.setForeground(new java.awt.Color(255, 255, 255));
        jButton_venda.setText("Efetuar Venda");
        jButton_venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_vendaMouseEntered(evt);
            }
        });
        jButton_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vendaActionPerformed(evt);
            }
        });

        jButton_fechar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_fechar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_fechar.setText("Fechar Caixa");
        jButton_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_fecharMouseEntered(evt);
            }
        });
        jButton_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fecharActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Comprar Produtos");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_funcionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_distribuidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_venda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_distribuidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_produtos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_venda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_funcionarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_fechar)
                    .addComponent(jButton2))
                .addGap(7, 7, 7))
        );

        jPanel2.setForeground(new java.awt.Color(255, 102, 0));

        jTextPane1.setFocusable(false);
        jTextPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextPane1MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_funcionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_funcionariosMouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><b>CONTROLE DE FUNCIONARIOS.</b><br>Incluindo todos as ações fundamentais do Software GEP (CRUD)<br> - Incluir Funcionario <br> - Remover Funcionario <br> - Alterar Funcionario <br> - Mostrar Funcionarios</html>");
    }//GEN-LAST:event_jButton_funcionariosMouseEntered

    private void jButton_distribuidoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_distribuidoresMouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><b>CONTROLE DE DISTRIBUIDORES.</b><br>Incluindo todos as ações fundamentais do Software GEP (CRUD)<br> - Incluir Distribuidor <br> - Remover Distribuidor <br> - Alterar Distribuidor <br> - Mostrar Distribuidores</html>");
    }//GEN-LAST:event_jButton_distribuidoresMouseEntered

    private void jButton_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_funcionariosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewFuncionarios tela_funcionarios = new ViewFuncionarios(null, false, user, caixa);
        tela_funcionarios.setTitle("Controle de Funcionario - Software GEP");
        tela_funcionarios.setVisible(true);

    }//GEN-LAST:event_jButton_funcionariosActionPerformed

    private void jTextPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1MouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html>             <b>Bem vindo(a) ao Menu Principal do Software GEP</b><br>INFORMAÇÃO GERAL SOBRE O MENU<br> - É possivel se encontrar informações obre cada funcionalidade ao passar o mouse sobre o botão da mesma.<br> - O sistema foi desenvolvido com o intuito de aprendizagem e desenvolvimento do Projeto Integrador. <br><b>O projeto foi desenvolvido por Luís Augusto Cardoso Mota</b></html>");
    }//GEN-LAST:event_jTextPane1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewLogin tela_login = new ViewLogin();
        tela_login.setTitle("Bem vindo ao Software GEP");
        tela_login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewProdutos tela_estoque = new ViewProdutos(null, false, user, caixa);
        tela_estoque.setTitle("Controle de Produtos - Software GEP");
        tela_estoque.setVisible(true);
    }//GEN-LAST:event_jButton_produtosActionPerformed

    private void jButton_produtosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_produtosMouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><b>CONTROLE DE PRODUTOS.</b><br>Incluindo todos as ações fundamentais do Software GEP (CRUD)<br> - Incluir Produto <br> - Remover Produto <br> - Alterar Produto <br> - Mostrar Produtos</html>");
    }//GEN-LAST:event_jButton_produtosMouseEntered

    private void jButton_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vendaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewVenda tela_venda = new ViewVenda(null, false, user, caixa);
        tela_venda.setTitle("Efetuação de Vendas - Software GEP");
        tela_venda.setVisible(true);
    }//GEN-LAST:event_jButton_vendaActionPerformed

    private void jButton_vendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_vendaMouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><b>VENDA DE PRODUTOS</b><br>Nesta seção é possivel realizar a venda de diversos produtos de 3 diferentes tipos<br> - Alimenticio <br> - Gerais <br> - Embalagens<br><b>O Sistema GEP conta com 3 Metodos de Pagamentos</b><br> - DEBITO <br> - CREDITO <br> - DINHEIRO</html>");
    }//GEN-LAST:event_jButton_vendaMouseEntered

    private void jButton_distribuidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_distribuidoresActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewDistribuidores t_distribuidor = new ViewDistribuidores(null, false, user, caixa);
        t_distribuidor.setTitle("Controle de Distribuidores - Software GEP");
        t_distribuidor.setVisible(true);
    }//GEN-LAST:event_jButton_distribuidoresActionPerformed

    private void jButton_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewFechar_Caixa t_fecha = new ViewFechar_Caixa(null, false, caixa);
        t_fecha.setTitle("Fechamento de Caixa - Software GEP");
        t_fecha.setVisible(true);
    }//GEN-LAST:event_jButton_fecharActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewCompra_Produto t_compra = new ViewCompra_Produto(null, false, caixa, user);
        t_compra.setTitle("Efetuação de Compras - Software GEP");
        t_compra.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><b>COMPRA DE PRODUTOS</b><br>Nesta seção é possivel realizar a compra de diversos produtos de 3 diferentes tipos<br> - Alimenticio <br> - Gerais <br> - Embalagens</html>");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_fecharMouseEntered
        // TODO add your handling code here:
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><b>FECHAMENTO DO CAIXA</b><br> Salva o saldo atual do caixa e gera um relatorio com COMPRAS e VENDAs efetuadas no DIA ATUAL</html>");
    }//GEN-LAST:event_jButton_fecharMouseEntered

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_distribuidores;
    private javax.swing.JButton jButton_fechar;
    private javax.swing.JButton jButton_funcionarios;
    private javax.swing.JButton jButton_produtos;
    private javax.swing.JButton jButton_venda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
