/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.UsuarioControle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Caixa;
import modelo.UserTipo;
import modelo.Usuario;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.GerarRelatorio;

/**
 *
 * @author zscrollock
 */
public class ViewFuncionarios extends javax.swing.JDialog {

    private Usuario user;
    private Caixa caixa;
    private Usuario user_aux;
    private UsuarioControle user_control = new UsuarioControle();
    /**
     * Creates new form ViewFuncionarios
     */
    public ViewFuncionarios(java.awt.Frame parent, boolean modal, Usuario user, Caixa caixa) {
        super(parent, modal);
        initComponents();
        this.user = user;
        this.caixa = caixa;
        this.setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent we){
                if(user.getTipo().equals(UserTipo.ADMINISTRADOR)){
                    jRadioButton_ger.setVisible(true);
                }else{
                    jRadioButton_ger.setVisible(false);
                }
                //Labels
                jLabel_nome_aux.setVisible(false);
                jLabel_login_aux.setVisible(false);
                jLabel_senha_aux.setVisible(false);
                jLabel_cpf_aux.setVisible(false);
                jLabel_telefone_aux.setVisible(false);
                jLabel_salario_aux.setVisible(false);
                jLabel_tipo_aux.setVisible(false);
                
                //Texts Fields
                jTextField_alt_cpf.setVisible(false);
                jTextField_alt_login.setVisible(false);
                jTextField_alt_nome.setVisible(false);
                jTextField_alt_salario.setVisible(false);
                jTextField_alt_senha.setVisible(false);
                jTextField_alt_tel.setVisible(false);
                jRadioButton_fun_aux.setVisible(false);
                jRadioButton_gen_aux.setVisible(false);
                jButton_alter.setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton_fun = new javax.swing.JRadioButton();
        jRadioButton_ger = new javax.swing.JRadioButton();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_salario = new javax.swing.JTextField();
        jTextField_login = new javax.swing.JTextField();
        jTextField_senha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_telefone = new javax.swing.JFormattedTextField();
        jTextField_cpf = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_cpf_aux = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_alter = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel_nome_aux = new javax.swing.JLabel();
        jLabel_cpf_aux = new javax.swing.JLabel();
        jLabel_telefone_aux = new javax.swing.JLabel();
        jLabel_login_aux = new javax.swing.JLabel();
        jLabel_senha_aux = new javax.swing.JLabel();
        jLabel_salario_aux = new javax.swing.JLabel();
        jRadioButton_fun_aux = new javax.swing.JRadioButton();
        jRadioButton_gen_aux = new javax.swing.JRadioButton();
        jLabel_tipo_aux = new javax.swing.JLabel();
        jButton_alter = new javax.swing.JButton();
        jTextField_alt_nome = new javax.swing.JTextField();
        jTextField_alt_login = new javax.swing.JTextField();
        jTextField_alt_senha = new javax.swing.JTextField();
        jTextField_alt_salario = new javax.swing.JTextField();
        jTextField_alt_cpf = new javax.swing.JFormattedTextField();
        jTextField_alt_tel = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Controle de Funcionários");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/Webp.net-resizeimage (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Salario");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefone");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Senha");

        buttonGroup1.add(jRadioButton_fun);
        jRadioButton_fun.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_fun.setText("Funcionario");

        buttonGroup1.add(jRadioButton_ger);
        jRadioButton_ger.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_ger.setText("Gerente");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar Funcionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Funcionario");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CPF");

        try {
            jTextField_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextField_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton_fun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_ger)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(121, 121, 121)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_telefone)
                                            .addComponent(jTextField_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton1)
                                                    .addComponent(jLabel9))
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_fun)
                    .addComponent(jRadioButton_ger)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Incluir Funcionario", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Digite o CPF do Funcionario que Deseja Remover");

        try {
            jTextField_cpf_aux.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField_cpf_aux.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar Funcionario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField_cpf_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cpf_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remover Funcionario", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Digite o CPF do Funcionario que deseja Alterar");

        try {
            jTextField_alter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buscar Funcionario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Cargo"
            }
        ));
        jTable3.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jLabel_nome_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome_aux.setText("Nome");

        jLabel_cpf_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cpf_aux.setText("CPF");

        jLabel_telefone_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefone_aux.setText("Telefone");

        jLabel_login_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_login_aux.setText("Login");

        jLabel_senha_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_senha_aux.setText("Senha");

        jLabel_salario_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_salario_aux.setText("Salario");

        buttonGroup2.add(jRadioButton_fun_aux);
        jRadioButton_fun_aux.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_fun_aux.setText("Funcionario");

        buttonGroup2.add(jRadioButton_gen_aux);
        jRadioButton_gen_aux.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_gen_aux.setText("Gerente");

        jLabel_tipo_aux.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tipo_aux.setText("Tipo de Funcionario");

        jButton_alter.setBackground(new java.awt.Color(51, 51, 51));
        jButton_alter.setForeground(new java.awt.Color(255, 255, 255));
        jButton_alter.setText("Confirmar Alteração");
        jButton_alter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterActionPerformed(evt);
            }
        });

        try {
            jTextField_alt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextField_alt_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_alter, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_nome_aux))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextField_alt_nome)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cpf_aux)
                            .addComponent(jButton5)
                            .addComponent(jLabel_senha_aux)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_alt_senha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_alt_cpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                    .addComponent(jLabel_login_aux)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton_fun_aux)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_gen_aux))
                    .addComponent(jLabel_tipo_aux)
                    .addComponent(jTextField_alt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_alter)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_telefone_aux)
                    .addComponent(jLabel_salario_aux)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_alt_salario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_alt_tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_alter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nome_aux)
                    .addComponent(jLabel_cpf_aux)
                    .addComponent(jLabel_telefone_aux, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_alt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_alt_cpf)
                    .addComponent(jTextField_alt_tel))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_login_aux)
                    .addComponent(jLabel_senha_aux)
                    .addComponent(jLabel_salario_aux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_alt_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_alt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_alt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_tipo_aux)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_fun_aux)
                            .addComponent(jRadioButton_gen_aux)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton_alter)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alterar Funcionario", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Cargo", "Salario"
            }
        ));
        jTable2.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exibir Funcionarios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Limpar tabela");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Gerar Relatorio de Funcionarios");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exibir Funcionarios", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 0));

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Voltar para o Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<Usuario> lista;
        String nome = jTextField_nome.getText();
        String cpf = jTextField_cpf.getText();
        String telefone = jTextField_telefone.getText();
        String login = jTextField_login.getText();
        String senha = jTextField_senha.getText();
        String aux_salario = jTextField_salario.getText();
        float salario;
            if(aux_salario.isEmpty()){
                salario = 0;
            }else{
                salario = Float.parseFloat(jTextField_salario.getText());
            }
        
        
        Usuario novoUser = new Usuario();
        UsuarioControle userControle = new UsuarioControle();
        
        if(!nome.equals("") || !cpf.equals("") || !telefone.equals("") || !login.equals("") || !senha.equals("")){
            if(!nome.equals(" ") || !cpf.equals(" ") || !telefone.equals(" ") || !login.equals(" ") || !senha.equals(" ")){
                novoUser.setNome(nome);
                novoUser.setCpf(cpf);
                novoUser.setTelefone(telefone);
                novoUser.setSalario(salario);
                novoUser.setLogin(login);
                novoUser.setSenha(senha);
               
                    if(jRadioButton_fun.isSelected()){
                        novoUser.setTipo(UserTipo.FUNCIONARIO);
                    }else if(jRadioButton_ger.isSelected()){
                        novoUser.setTipo(UserTipo.GERENTE);
                    }else{
                        JOptionPane.showMessageDialog(null, "Selecione o tipo de Funcionario", "Alerta", JOptionPane.WARNING_MESSAGE);
                    }
                    lista = userControle.findByCpf(cpf);
                        if(lista.isEmpty()){
                            userControle.inserir(novoUser);
                            JOptionPane.showMessageDialog(null, "Dados gravados com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                            jTextField_nome.setText("");
                            jTextField_cpf.setText("");
                            jTextField_telefone.setText("");
                            jTextField_salario.setText("");
                            jTextField_login.setText("");
                            jTextField_senha.setText("");
                            buttonGroup1.clearSelection();
                        }else{
                            JOptionPane.showMessageDialog(null, "CPF ja cadastrado", "Alerta", JOptionPane.WARNING_MESSAGE);
                            jTextField_cpf.setText("");
                            jTextField_cpf.requestFocus();
                        }               
            }else{
                JOptionPane.showMessageDialog(null, "Campos incompletos", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campos incompletos", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        List<Usuario> user_remove;
        UsuarioControle user_controle = new UsuarioControle();
        String cpf_aux = jTextField_cpf_aux.getText();
        DefaultTableModel unique_user = (DefaultTableModel) jTable1.getModel();
        
        if(!cpf_aux.equals("") || !cpf_aux.equals(" ")){
            user_remove = user_controle.findByCpf(cpf_aux);
            if(!user_remove.isEmpty()){
                Usuario usuario = user_remove.get(user_remove.size()-1);
                unique_user.addRow(new Object[]{usuario.getNome(), usuario.getCpf(), usuario.getTelefone(), usuario.getTipo()});
                int result = JOptionPane.showConfirmDialog(null, "Deseja remover esse funcionario?", "Sim ou não?", JOptionPane.YES_NO_OPTION);
                if(usuario.getCpf().equals(this.user.getCpf()) || usuario.getTipo().equals(this.user.getTipo().ADMINISTRADOR)){
                    JOptionPane.showMessageDialog(null, "Não é possivel remover o proprio registro, ou super usuarios", "Alerta", JOptionPane.WARNING_MESSAGE);
                    jTextField_cpf_aux.setText("");
                    jTextField_cpf_aux.requestFocus();
                }else{
                    if(result == JOptionPane.YES_OPTION){
                        user_controle.remover(usuario);
                        JOptionPane.showMessageDialog(null, "Funcionario removido com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                        jTextField_cpf_aux.setText("");
                        jTextField_cpf_aux.requestFocus();
                        unique_user.setRowCount(0);
                    }else{
                        JOptionPane.showMessageDialog(null, "Não foi possivel remover o Funcionario", "Alerta", JOptionPane.WARNING_MESSAGE);
                        jTextField_cpf_aux.setText("");
                        jTextField_cpf_aux.requestFocus();
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Não foi encontrado Funcionarios com esse CPF", "Alerta", JOptionPane.WARNING_MESSAGE);
                jTextField_cpf_aux.setText("");
                jTextField_cpf_aux.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Insira dados no campo de CPF do Funcionario", "Alerta", JOptionPane.WARNING_MESSAGE);
            jTextField_cpf_aux.setText("");
            jTextField_cpf_aux.requestFocus(); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UsuarioControle user_control = new UsuarioControle();
        List<Usuario> list_users = user_control.findAll();
        DefaultTableModel all_users = (DefaultTableModel) jTable2.getModel();
        
        for(Usuario u : list_users){
            all_users.addRow(new Object[]{u.getNome(), u.getCpf(), u.getTelefone(), u.getTipo(), u.getSalario()});
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel all_users = (DefaultTableModel) jTable2.getModel();
        all_users.setRowCount(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       UsuarioControle user_control = new UsuarioControle();
        List<Usuario> list_users;
        DefaultTableModel all_users = (DefaultTableModel) jTable3.getModel();
        String cpf = jTextField_alter.getText();
        
        if(!jTextField_alter.equals("") || !jTextField_alter.equals(" ")){
            list_users = user_control.findByCpf(cpf);
            this.user_aux = list_users.get(list_users.size()-1);
            if(!list_users.isEmpty()){   
                all_users.addRow(new Object[]{this.user_aux.getNome(), this.user_aux.getCpf(), this.user_aux.getTelefone(), this.user_aux.getTipo()});
                
                //Labels
                jLabel_nome_aux.setVisible(true);
                jLabel_login_aux.setVisible(true);
                jLabel_senha_aux.setVisible(true);
                jLabel_cpf_aux.setVisible(true);
                jLabel_telefone_aux.setVisible(true);
                jLabel_salario_aux.setVisible(true);
                jLabel_tipo_aux.setVisible(true);
                
                //Texts Fields
                jTextField_alt_cpf.setVisible(true);
                jTextField_alt_login.setVisible(true);
                jTextField_alt_nome.setVisible(true);
                jTextField_alt_salario.setVisible(true);
                jTextField_alt_senha.setVisible(true);
                jTextField_alt_tel.setVisible(true);
                jRadioButton_fun_aux.setVisible(true);
                jRadioButton_gen_aux.setVisible(true);
                jButton_alter.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(null, "Não foi encontrado Funcionarios com esse CPF", "Alerta", JOptionPane.WARNING_MESSAGE);
                jTextField_alter.setText("");
                jTextField_alter.requestFocus();
            }
        }else{
           JOptionPane.showMessageDialog(null, "Insira dados no campo de CPF do Funcionario", "Alerta", JOptionPane.WARNING_MESSAGE);
           jTextField_alter.setText("");
           jTextField_alter.requestFocus(); 
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton_alterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterActionPerformed
        // TODO add your handling code here:
        String nome = jTextField_alt_nome.getText();
        String cpf = jTextField_alt_cpf.getText();
        String telefone = jTextField_alt_tel.getText();
        String login = jTextField_alt_login.getText();
        String senha = jTextField_alt_senha.getText();
        String aux_salario = jTextField_alt_salario.getText();
        float salario;
            if(aux_salario.isEmpty()){
                salario = 0;
            }else{
                salario = Float.parseFloat(jTextField_alt_salario.getText());
            }
        if(!nome.equals("") || !cpf.equals("") || !telefone.equals("") || !login.equals("") || !senha.equals("")){
            if(!nome.equals(" ") || !cpf.equals(" ") || !telefone.equals(" ") || !login.equals(" ") || !senha.equals(" ")){
                this.user_aux.setCpf(cpf);
                this.user_aux.setNome(nome);
                this.user_aux.setTelefone(telefone);
                this.user_aux.setLogin(login);
                this.user_aux.setSenha(senha);
                this.user_aux.setSalario(salario);
                if(jRadioButton_fun_aux.isSelected()){
                    this.user_aux.setTipo(UserTipo.FUNCIONARIO);
                }else{
                    this.user_aux.setTipo(UserTipo.GERENTE);
                }
                UsuarioControle user_control = new UsuarioControle();
                user_control.alterar(this.user_aux);
                JOptionPane.showMessageDialog(null, "Dados gravados com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                
                //Labels
                jLabel_nome_aux.setVisible(false);
                jLabel_login_aux.setVisible(false);
                jLabel_senha_aux.setVisible(false);
                jLabel_cpf_aux.setVisible(false);
                jLabel_telefone_aux.setVisible(false);
                jLabel_salario_aux.setVisible(false);
                jLabel_tipo_aux.setVisible(false);
                
                //Texts Fields
                jTextField_alt_cpf.setVisible(false);
                jTextField_alt_login.setVisible(false);
                jTextField_alt_nome.setVisible(false);
                jTextField_alt_salario.setVisible(false);
                jTextField_alt_senha.setVisible(false);
                jTextField_alt_tel.setVisible(false);
                jRadioButton_fun_aux.setVisible(false);
                jRadioButton_gen_aux.setVisible(false);
                jButton_alter.setVisible(false);
                
                jTextField_alt_cpf.setText("");
                jTextField_alt_login.setText("");
                jTextField_alt_nome.setText("");
                jTextField_alt_salario.setText("");
                jTextField_alt_senha.setText("");
                jTextField_alt_tel.setText("");
                buttonGroup2.clearSelection();
                jTextField_alter.setText("");
                DefaultTableModel all_users = (DefaultTableModel) jTable3.getModel();
                all_users.setRowCount(0);
            }
        }
    }//GEN-LAST:event_jButton_alterActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            List<Usuario> lista = this.user_control.findByTipoFun();
            GerarRelatorio relatorio = new GerarRelatorio();
            JasperPrint jp = relatorio.gerarFromList("/relatorio/relatorio_funcionarios.jasper", lista);
            new JasperViewer(jp,false).setVisible(true);
            
        }catch(JRException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewMenuPrincipal menu_p = new ViewMenuPrincipal(null, true, user, caixa);
        menu_p.setTitle("Menu Principal - Software GEP");
        menu_p.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_alter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_cpf_aux;
    private javax.swing.JLabel jLabel_login_aux;
    private javax.swing.JLabel jLabel_nome_aux;
    private javax.swing.JLabel jLabel_salario_aux;
    private javax.swing.JLabel jLabel_senha_aux;
    private javax.swing.JLabel jLabel_telefone_aux;
    private javax.swing.JLabel jLabel_tipo_aux;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton_fun;
    private javax.swing.JRadioButton jRadioButton_fun_aux;
    private javax.swing.JRadioButton jRadioButton_gen_aux;
    private javax.swing.JRadioButton jRadioButton_ger;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JFormattedTextField jTextField_alt_cpf;
    private javax.swing.JTextField jTextField_alt_login;
    private javax.swing.JTextField jTextField_alt_nome;
    private javax.swing.JTextField jTextField_alt_salario;
    private javax.swing.JTextField jTextField_alt_senha;
    private javax.swing.JFormattedTextField jTextField_alt_tel;
    private javax.swing.JFormattedTextField jTextField_alter;
    private javax.swing.JFormattedTextField jTextField_cpf;
    private javax.swing.JFormattedTextField jTextField_cpf_aux;
    private javax.swing.JTextField jTextField_login;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_salario;
    private javax.swing.JTextField jTextField_senha;
    private javax.swing.JFormattedTextField jTextField_telefone;
    // End of variables declaration//GEN-END:variables
}
