/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CaixaControle;
import controle.ProdutoControle;
import controle.VendaControle;
import controle.Venda_produtoControle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Caixa;
import modelo.Produto;
import modelo.Usuario;
import modelo.Venda;
import modelo.VendaTipoPagmt;
import modelo.Venda_Produto;

/**
 *
 * @author zscrollock
 */
public class ViewVenda extends javax.swing.JDialog {
    
    private Usuario user;
    private Venda venda;
    private Produto produto;
    private Caixa caixa;
    private int qtd_total = 0;
    private float valor_total = 0;
    private long count_vendas = 0;
    /**
     * Creates new form ViewVenda
     */
    public ViewVenda(java.awt.Frame parent, boolean modal, Usuario user, Caixa caixa) {
        super(parent, modal);
        initComponents();
        this.user = user;
        this.caixa = caixa;
        this.setLocationRelativeTo(null);
        VendaControle v_control = new VendaControle();
        
        addWindowListener(new WindowAdapter() {
        @Override
            public void windowOpened(WindowEvent we){
                Date dataAtual = Calendar.getInstance().getTime();
                
                DateFormat dateFormat = new SimpleDateFormat("dd - MM - yyyy | hh:mm:ss");
                VendaControle v_control = new VendaControle();
                
                count_vendas = v_control.countVendas();
                jLabel_count.setText("Numero da Venda: " + count_vendas);
                
                jLabel_fun.setText("Nome do Funcionario: " + user.getNome());
                jLabel_data.setText("Data Atual: " + dateFormat.format(dataAtual));
                
                venda = new Venda();
                
                venda.setData(new Date());
                venda.setFuncionario(user);
                venda.setTipoPagmt(VendaTipoPagmt.DINHEIRO);
                venda.setValortotal(0);
                
                v_control.inserir(venda);
            }
            
            @Override
            public void windowClosing(WindowEvent e){
                CaixaControle c_control = new CaixaControle();
                v_control.remover(venda);
                
                ViewMenuPrincipal menu = new ViewMenuPrincipal(null, false, user, caixa);
                menu.setVisible(true);
            } 
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_fun = new javax.swing.JLabel();
        jLabel_count = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_data = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_qtd = new javax.swing.JLabel();
        jLabel_valor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_cod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_preco = new javax.swing.JTextField();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_qtd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Venda de Produtos");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/carrinho.png"))); // NOI18N

        jLabel_fun.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_fun.setText("Nome do Funcionario: ");

        jLabel_count.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_count.setText("Numero da Venda:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_fun)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel_count)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_fun)
                            .addComponent(jLabel_count)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        jLabel_data.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_data.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_data)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_data)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço Un.", "Quantidade", "Tipo", "Sub-Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel_qtd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_qtd.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_qtd.setText("Quantidade de Itens:");

        jLabel_valor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_valor.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_valor.setText("Valor total:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Código do Produto");

        jTextField_cod.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nome do Produto");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Preço Un.");

        jTextField_preco.setEditable(false);
        jTextField_preco.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_preco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_preco.setForeground(new java.awt.Color(255, 255, 255));

        jTextField_nome.setEditable(false);
        jTextField_nome.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_nome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_nome.setForeground(new java.awt.Color(255, 255, 255));

        jTextField_qtd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Quantidade");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Adicionar ao Carrinho");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Itens no Carrinho");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Finalizar Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_cod, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jTextField_nome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField_qtd)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_qtd)
                                    .addComponent(jLabel_valor))
                                .addGap(77, 77, 77)
                                .addComponent(jButton3)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_qtd, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jTextField_preco))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_qtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_valor))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jTextField_cod.getText());
        
        if(!jTextField_cod.getText().equals("")){
            if(!jTextField_cod.getText().equals(" ")){
                ProdutoControle prod_control = new ProdutoControle();
                List<Produto> lista_prod = prod_control.findByCode(codigo);
                if(!lista_prod.isEmpty()){
                    this.produto = lista_prod.get(lista_prod.size()-1);
                    if(produto.getQuantidade() <= produto.getQuantidade_min()){
                        this.produto = null;
                        JOptionPane.showMessageDialog(null, "Produto Indisponivel", "Alerta", JOptionPane.WARNING_MESSAGE);
                        jTextField_cod.setText("");
                    }else{
                        jTextField_nome.setText(this.produto.getNome());
                        jTextField_preco.setText(Float.toString(this.produto.getPreco()));
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi encontrado produto com esse código", "Alerta", JOptionPane.WARNING_MESSAGE);
                    jTextField_cod.setText("");
                    jTextField_cod.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
                jTextField_cod.setText("");
                jTextField_cod.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
            jTextField_cod.setText("");
            jTextField_cod.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Venda_produtoControle itens_control = new Venda_produtoControle();
        Venda_Produto item = new Venda_Produto();
        List<Venda_Produto> venda_prod_list;
        
        int quantidade = Integer.parseInt(jTextField_qtd.getText());
        float v_tot = this.produto.getPreco() * quantidade;
        DefaultTableModel itens = (DefaultTableModel) jTable1.getModel();
        itens.addRow(new Object[]{this.produto.getNome(),this.produto.getPreco(), quantidade, this.produto.getTipo(), v_tot});
        
        qtd_total = qtd_total + quantidade;
        valor_total = valor_total + v_tot;
        
        venda_prod_list = itens_control.existProduct(produto.getIdProduto(), venda.getIdVenda());
        if(venda_prod_list.isEmpty()){            
            item.setProduto(produto);
            item.setVenda(venda);
            item.setQuantidade(quantidade);
            item.setValortotal(v_tot);

            itens_control.inserir(item);
            jTextField_qtd.setText("");
            jLabel_valor.setText("Valor total: " + valor_total);
            jLabel_qtd.setText("Quantidade de Itens: " + qtd_total);
        }else{          
            item.setProduto(produto);
            item.setVenda(venda);
            item.setQuantidade(item.getQuantidade() + quantidade);
            v_tot = this.produto.getPreco() * item.getQuantidade();
            item.setValortotal(v_tot);

            itens_control.alterar(item);
            jTextField_qtd.setText("");
            jLabel_valor.setText("Valor total: " + valor_total);
            jLabel_qtd.setText("Quantidade de Itens: " + qtd_total);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VendaControle v_control = new VendaControle();
        CaixaControle c_control = new CaixaControle();
        Caixa c_aux = new Caixa();
        List<Caixa> l;
        venda.setValortotal(valor_total);
        v_control.alterar(venda);
        
        jTextField_cod.setText("");
        jTextField_qtd.setText("");
        
        l = c_control.isOpen();
        c_aux = l.get(l.size()-1);
        
        c_aux.setVenda(venda);
        c_aux.setCompra(null);
        c_aux.setSaldo_fechamento(c_aux.getSaldo_fechamento() + valor_total);
        c_control.inserir(c_aux);
        
        valor_total = 0;
        qtd_total = 0;
        
        this.dispose();
        ViewFormaPagmto pagmt = new ViewFormaPagmto(null, false, venda, user, caixa);
        pagmt.setTitle("Escolha a Forma de Pagamento - Software GEP");
        pagmt.setVisible(true);
        
        count_vendas = v_control.countVendas();
        jLabel_count.setText("Numero da Venda: " + count_vendas);
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_count;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_fun;
    private javax.swing.JLabel jLabel_qtd;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_cod;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_preco;
    private javax.swing.JTextField jTextField_qtd;
    // End of variables declaration//GEN-END:variables
}
