/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CaixaControle;
import controle.CompraControle;
import controle.Compra_ProdutoControle;
import controle.DistribuidorControle;
import controle.ProdutoControle;
import controle.Venda_produtoControle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Caixa;
import modelo.Compra;
import modelo.Compra_Produto;
import modelo.Distribuidor;
import modelo.Produto;
import modelo.Usuario;

/**
 *
 * @author zscrollock
 */
public class ViewCompra_Produto extends javax.swing.JDialog {

    private Caixa caixa;
    private Usuario user;
    private Compra compra;
    private Produto produto;
    private Distribuidor distribuidor;
    private int qtd_total = 0;
    private float valor_total = 0;
    /**
     * Creates new form ViewCompra_Produto
     */
    public ViewCompra_Produto(java.awt.Frame parent, boolean modal, Caixa caixa, Usuario user) {
        super(parent, modal);
        initComponents();
        this.caixa = caixa;
        this.user = user;
        CompraControle compra_control = new CompraControle();
        
        addWindowListener(new WindowAdapter() {
        @Override
            public void windowOpened(WindowEvent we){
                Date dataAtual = Calendar.getInstance().getTime();
                CaixaControle c_control = new CaixaControle();
                CompraControle compra_control = new CompraControle();
                distribuidor = new Distribuidor();
                
                compra = new Compra();
                compra.setData(dataAtual);
                compra.setValortotal(0);
                compra.setDistribuidor(null);
                compra_control.inserir(compra);
                
            }
            @Override
            public void windowClosing(WindowEvent e){
                compra_control.remover(compra);
                ViewMenuPrincipal menu = new ViewMenuPrincipal(null, false, user, caixa);
                menu.setTitle("Menu Principal - Software GEP");
                menu.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_cod = new javax.swing.JTextField();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_preco = new javax.swing.JTextField();
        jTextField_qtd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel_valor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_cod_dist = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Compra de Produtos dos Distribuidores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Distribuidor", "Produto", "Preço Un.", "Quantidade", "Tipo", "Sub total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField_nome.setEditable(false);
        jTextField_nome.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_nome.setForeground(new java.awt.Color(255, 255, 255));

        jTextField_preco.setEditable(false);
        jTextField_preco.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_preco.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preço Un.");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome do Produto");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Digite o Codigo do Produto");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adicionar item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Finalizar Compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel_valor.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_valor.setText("Valor total da Compra");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo do Distribuidor");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome do Distribuidor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_cod_dist, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextField_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 106, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_valor)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(177, 177, 177))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_cod_dist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int codigo = Integer.parseInt(jTextField_cod.getText());
        
        if(!jTextField_cod.getText().equals("")){
            if(!jTextField_cod.getText().equals(" ")){
                ProdutoControle prod_control = new ProdutoControle();
                List<Produto> lista_prod = prod_control.findByCode(codigo);
                if(!lista_prod.isEmpty()){
                    this.produto = lista_prod.get(lista_prod.size()-1);
                    jTextField_cod.setText("");
                    jTextField_nome.setText(this.produto.getNome());
                    jTextField_preco.setText(Float.toString(this.produto.getPreco()));
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi encontrado produto com esse código", "Alerta", JOptionPane.WARNING_MESSAGE);
                    jTextField_cod.setText("");
                    jTextField_cod.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
                jTextField_cod.setText("");
                jTextField_cod.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
            jTextField_cod.setText("");
            jTextField_cod.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jTextField_cod_dist.getText());
        String nome;
        CompraControle compra_control = new CompraControle();
        
        if(!jTextField_cod_dist.getText().equals("")){
            if(!jTextField_cod_dist.getText().equals(" ")){
                DistribuidorControle dist_control = new DistribuidorControle();
                List<Distribuidor> lista = dist_control.findById(codigo);
                if(!lista.isEmpty()){
                    this.distribuidor = lista.get(lista.size()-1);
                    nome = this.distribuidor.getNome();
                    jTextField_cod_dist.setText("");
                    jTextField1.setText(nome);
                    compra.setDistribuidor(distribuidor);
                    compra_control.alterar(compra);
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi encontrado distribuidor com esse código", "Alerta", JOptionPane.WARNING_MESSAGE);
                    jTextField_cod.setText("");
                    jTextField_cod.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
                jTextField_cod.setText("");
                jTextField_cod.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete os campos obrigatórios", "Alerta", JOptionPane.WARNING_MESSAGE);
            jTextField_cod.setText("");
            jTextField_cod.requestFocus();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Compra_ProdutoControle itens_control = new Compra_ProdutoControle();
        Compra_Produto item = new Compra_Produto();
        List<Compra_Produto> venda_prod_list;
        
        int quantidade = Integer.parseInt(jTextField_qtd.getText());
        float v_tot = this.produto.getPreco() * quantidade;
        DefaultTableModel itens = (DefaultTableModel) jTable1.getModel();
        itens.addRow(new Object[]{this.distribuidor.getNome(),this.produto.getNome(),this.produto.getPreco(), quantidade, this.produto.getTipo(), v_tot});
        
        valor_total = valor_total + v_tot;
        
        venda_prod_list = itens_control.existProduct(produto.getIdProduto(), compra.getIdCompra());
        if(venda_prod_list.isEmpty()){            
            item.setProduto(produto);
            item.setCompra(compra);
            item.setQuantidade(quantidade);
            item.setValortotal(v_tot);

            itens_control.inserir(item);
            jTextField_qtd.setText("");
            jTextField1.setText("");
            jLabel_valor.setText("Valor total: " + valor_total);
        }else{          
            item.setProduto(produto);
            item.setCompra(compra);
            item.setQuantidade(quantidade);
            v_tot = this.produto.getPreco() * item.getQuantidade();
            item.setValortotal(v_tot);

            itens_control.alterar(item);
            jTextField_qtd.setText("");
            jLabel_valor.setText("Valor total: " + valor_total);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CompraControle c_control = new CompraControle();
        CaixaControle caixa_control = new CaixaControle();
        Caixa c_aux = new Caixa();
        List<Caixa> l;
        compra.setValortotal(valor_total);
        c_control.alterar(compra);
        
        jTextField_cod.setText("");
        jTextField_cod_dist.setText("");
        jTextField_qtd.setText("");
        
        l = caixa_control.isOpen();
        c_aux = l.get(l.size()-1);
        
        c_aux.setCompra(compra);
        c_aux.setVenda(null);
        c_aux.setSaldo_fechamento(c_aux.getSaldo_fechamento() - valor_total);
        caixa_control.inserir(c_aux);
        valor_total = 0;
        
        this.dispose();
        ViewMenuPrincipal menu = new ViewMenuPrincipal(null, false, user, caixa);
        menu.setTitle("Menu Principal - Software GEP");
        menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_cod;
    private javax.swing.JTextField jTextField_cod_dist;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_preco;
    private javax.swing.JTextField jTextField_qtd;
    // End of variables declaration//GEN-END:variables
}
